CREATE DATABASE DOLCE;

CREATE TABLE PIZZA (
    ID SERIAL PRIMARY KEY UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CHECK (PRICE>10)
);

CREATE TABLE ORDER_TAKES_PIZZA (
    ID_PIZZA INT NOT NULL,
    ID_ORDER INT NOT NULL,
    QTY INT NOT NULL,
    PRICE DECIMAL(10, 2),
    DISCOUNT DECIMAL(5, 2),
    PRIMARY KEY (ID_PIZZA, ID_ORDER)
);


CREATE TABLE CUSTOMERS (
    NUM SERIAL NOT NULL PRIMARY KEY UNIQUE,
    NIF VARCHAR(20) NOT NULL,
    F_NAME VARCHAR(50) NOT NULL,
    L_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PHONE_NUMBER INT NOT NULL,
    CHECK (phone_number BETWEEN 600000000 AND 999999999)
);

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY UNIQUE,
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CUSTOMER INT NOT NULL
);

INSERT INTO CUSTOMERS (NUM, NIF, F_NAME, L_NAME, ADDRESS, PHONE_NUMBER)
VALUES (1, 43000011, 'alejandro', 'vives', 'calle de misco 15', 651111414), 
(2, 43000022, 'bernardo', 'ojuela', 'calle de jones 3 34', 684232525),
(3, 43000033, 'andres', 'martin', 'calle jaime III 5 32', 678596325),
(4, 43000044, 'antonio', 'vermejo', 'calle aragon 20', 648585858),
(5, 43000055, 'alejandro', 'hernandez', 'calle de misco', 651111414);

INSERT INTO PIZZA (ID, NAME, DESCRIPTION, PRICE)
VALUES (1, 'margarita', 'masa, con tomate y mozzarella', '10.99'),
(2, 'peperoni', 'masa, tomate, mozzarella y peperoni', '13.99'),
(3, '4quesos', 'masa, tomate, mozzarella, edam, roquefort y gorgonzola', '13.99'),
(4, '3ladrones', 'masa, tomate, mozzarella, jamon, bacon y serrano', '13.99'),
(5, 'peperoniF', 'masa, tomate, mozarella, peperoni', '19.50');



INSERT INTO ORDERS (ID, ID_CUSTOMER,) 
VALUES (1, 1),
(2, 2),
(3, 2),
(4, 3),
(5, 4);





INSERT INTO ORDER_TAKES_PIZZA ( ID_PIZZA, ID_ORDER, QTY, PRICE, DISCOUNT)
VALUES ( 1, 1, 1, 10.99, 0);
( 2, 2, 3, '41.97', 0),
( 5, 3, 1, '27.98', 0),
( 3, 4, 1, '27.98', 0),
( 3, 5, 1, '27.98', 0);


ALTER TABLE ORDER_TAKES_PIZZA
ADD CONSTRAINT FK_ORDERS_TAKE_PIZZA
FOREIGN KEY (ID_PIZZA) REFERENCES PIZZA (ID) ON DELETE CASCADE;

ALTER TABLE ORDER_TAKES_PIZZA
ADD CONSTRAINT FK_PIZZA_TAKES_ORDER
FOREIGN KEY (ID_ORDERS) REFERENCES ORDERS (ID) ON DELETE SET DEFAULT;

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ID_CUSTOMER
FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (NIF) ON DELETE CASCADE set NULL;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT ORDER_ID
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID);

ALTER TABLE ORDER_TAKES_PIZZA
ALTER COLUMN price SET DEFAULT '00';

ALTER TABLE ORDER_TAKES_PIZZA
ALTER DISCOUNT price SET DEFAULT '00';

ALTER TABLE ORDERS 
ADD COLUMN DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
































-- Crear la tabla Pizza
CREATE TABLE PIZZA (
    ID_PIZZA INT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL CHECK (PRECIO > 0),
    INGREDIENTES VARCHAR(255) NOT NULL
);

-- Crear la tabla Cliente
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY NOT NULL UNIQUE,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL UNIQUE
);

-- Crear la tabla Pedido
CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY NOT NULL,
    ID_PIZZA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PIZZA) REFERENCES PIZZA(ID_PIZZA) ON DELETE CASCADE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE SET NULL
);